### ISSUE TITLE
search args

### ISSUE THREAD

**Issue by aml35** [jasperdavey/CS490Project#28] opened 2016-04-17 17:31 UTC
Input : text, type

type should be either "Users" or "Events"

text should be any text. (Example: Jasper, Devin, Dev, devin, 05, 2016, A, a, angelica, angel, .....)

search will then look in either Users or Events tables according to 'type' and collect events that matches the 'text' field.

**Comment by tramrattan** [comment] 2016-04-17 18:54
not working for me

sending args:
command=12&text=search&type=Events

getting back : 
{"status":404,"message":"Error: Search text empty.","":[null]}

# don not send back null for any response, make it an empty array or an empty string

# also do not start argument with capital letters, make all lower case, i.e Events should just be events

**Comment by aml35** [comment] 2016-04-17 19:42
changed "Events" to "events" as you asked and same for "Users"

this is the code I am using for testing search.php:

<!DOCTYPE html>
<html>
<head>
<title>Search Box Example 1</title>
<meta name="ROBOTS" content="NOINDEX, NOFOLLOW" />

<style type="text/css">
	#tfheader{
		background-color:#c3dfef;
	}
	#tfnewsearch{
		float:right;
		padding:20px;
	}
	.tftextinput{
		margin: 0;
		padding: 5px 15px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:14px;
		border:1px solid #0076a3; border-right:0px;
		border-top-left-radius: 5px 5px;
		border-bottom-left-radius: 5px 5px;
	}
	.tfbutton {
		margin: 0;
		padding: 5px 15px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:14px;
		outline: none;
		cursor: pointer;
		text-align: center;
		text-decoration: none;
		color: #ffffff;
		border: solid 1px #0076a3; border-right:0px;
		background: #0095cd;
		background: -webkit-gradient(linear, left top, left bottom, from(#00adee), to(#0078a5));
		background: -moz-linear-gradient(top,  #00adee,  #0078a5);
		border-top-right-radius: 5px 5px;
		border-bottom-right-radius: 5px 5px;
	}
	.tfbutton:hover {
		text-decoration: none;
		background: #007ead;
		background: -webkit-gradient(linear, left top, left bottom, from(#0095cc), to(#00678e));
		background: -moz-linear-gradient(top,  #0095cc,  #00678e);
	}
	/* Fixes submit button height problem in Firefox */
	.tfbutton::-moz-focus-inner {
	  border: 0;
	}
	.tfclear{
		clear:both;
	}
</style>
</head>
<body>
	
	<div id="tfheader">
		<form id="tfnewsearch" method="POST" action="search.php">
				<input type="radio" name="type" value="users"> Users
				<input type="radio" name="type" value="events"> Events<br>
		        <input type="text"  name="text" size="21" maxlength="120"><input type="submit" value="search" class="tfbutton">
		</form>
	<div class="tfclear"></div>
	</div>
</body>
</html>

**Comment by aml35** [comment] 2016-04-17 19:53
I did the changes you asked me. Try again.

you also can test it from this url:

https://web.njit.edu/~aml35/login/searchBAR.html

**Comment by tramrattan** [comment] 2016-04-17 21:36
In your test example you are calling your search.php file, the issue is probably when I am sending it to your commandLine.php file. Testing calls to your commandLine.php  this is probably where all the issues lie that we have been having. 

also if an item that I am searching for does not exists, just send back and empty array,
and just send a json like {"results": [ ] } , where the array will be filled with what ever I search for
i will know if the items in the array are events or users

**Comment by aml35** [comment] 2016-04-18 01:11
I changed it to {"results":[]} as you asked

I created a test case calling my commandLine.php and still works

you can see it here:

https://web.njit.edu/~aml35/login/display.html

**Comment by aml35** [comment] 2016-04-18 01:14
command=12&text="angel"&type="users"

the output is:

{"results":[{"id":"8",
"firstname":"Angelica",
"lastname":"Llerena",
"username":"aml35",
"email":"llerena@njit.edu",
"bio":"",
"image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg",
"events":"",
"friends":"",
"createdEvents":"8",
"pendingFriendRequests":"",
"tags":""}]}

**Comment by aml35** [comment] 2016-04-18 01:53
Here is the new output, just for testing:

Welcome to SEARCH:
text: angel
type: users
{"results":[{"id":"8",
"firstname":"Angelica",
"lastname":"Llerena",
"username":"aml35",
"email":"llerena@njit.edu",
"bio":"","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg",
"events":"",
"friends":"",
"createdEvents":"8",
"pendingFriendRequests":"",
"tags":""}]}

**Comment by tramrattan** [comment] 2016-04-18 01:53
empty($searchText) // what does this code do ?

**Comment by tramrattan** [comment] 2016-04-18 01:54
sending 
command=12&text=test&type=users

response 
Welcome to SEARCH:<br>text: <br>type: <br>{"status":404,"results":["Error: Search text empty."]}

**Comment by aml35** [comment] 2016-04-18 01:55
empty checks if text or type are empty

if true returns the above output you just sent me

**Comment by tramrattan** [comment] 2016-04-18 01:56
isset(_POST('text')) 

and isset(_POST('type'))

is all you need

**Comment by aml35** [comment] 2016-04-18 01:59
I changed it, but still that should no make a difference

**Comment by tramrattan** [comment] 2016-04-18 02:00
Returns FALSE if var exists and has a non-empty, non-zero value. Otherwise returns TRUE.

should be !empty( <var>)

**Comment by aml35** [comment] 2016-04-18 02:03
I removed it, just left !isset()

**Comment by aml35** [comment] 2016-04-18 13:57
Are you still having issues or can I close this issue?

**Comment by tramrattan** [comment] 2016-04-18 14:02
It works when I use JavaScript to test it, it could be that the keywords
you use, text or type are keyboard for curl . But you can close it

**Closed as completed** 2016-04-18 14:04 UTC
Labels: bug
